#!/usr/bin/env bash

echo "Starting Kong 12-factor config"

SRC_DIR=/app
BIN_DIR=$(cd "$(dirname "$0")"; pwd)

# Get the private IP of the dyno.
# Fallback to localhost for the common runtime.
export KONG_CLUSTER_PRIVATE_IP=$(ip -4 -o addr show dev eth1)
if [ "$KONG_CLUSTER_PRIVATE_IP" ]
then
  KONG_CLUSTER_PRIVATE_IP=$(echo $KONG_CLUSTER_PRIVATE_IP | awk '{print $4}' | cut -d/ -f1)
else
  KONG_CLUSTER_PRIVATE_IP='127.0.0.1'
fi
echo "Kong cluster private IP: $KONG_CLUSTER_PRIVATE_IP"

# Specify template to use for non-web processes or use default.
# For use with exposing to private space network
if ! [ -z "$1" ] && [ -f "$SRC_DIR/config/$1-kong.conf.etlua" ] then
  echo "Overwriting kong.conf for non-web process"
  template_filename="$1-kong.conf.etlua"
else
  template_filename="kong.conf.etlua"
fi

luajit $SRC_DIR/config/kong-12f.lua $SRC_DIR/config/$template_filename $SRC_DIR $1

# export the variables generated by `kong-12f.lua`
source $SRC_DIR/.profile.d/kong-env
