#!/usr/bin/env bash

echo "Starting Kong 12-factor config"

SRC_DIR=/app
BIN_DIR=$(cd "$(dirname "$0")"; pwd)

# Get the private IP of the dyno.
# Fallback to localhost for the common runtime.
export KONG_CLUSTER_PRIVATE_IP=$(ip -4 -o addr show dev eth1)
if [ "$KONG_CLUSTER_PRIVATE_IP" ]
then
  KONG_CLUSTER_PRIVATE_IP=$(echo $KONG_CLUSTER_PRIVATE_IP | awk '{print $4}' | cut -d/ -f1)
else
  KONG_CLUSTER_PRIVATE_IP='127.0.0.1'
fi
echo "Kong cluster private IP: $KONG_CLUSTER_PRIVATE_IP"

# Specify template to use for non-web processes or use default.
# For use with exposing to private space network
PROC=$(echo $DYNO | cut -f1 -d".")
if [ -f "$SRC_DIR/config/$PROC-kong.conf.etlua" ]
then
  template_filename="$PROC-kong.conf.etlua"
else
  template_filename="kong.conf.etlua"
fi

echo "Writing kong.conf using $template_filename"
luajit $SRC_DIR/config/kong-12f.lua $SRC_DIR/config/$template_filename $SRC_DIR $PROC
# export the variables generated by `kong-12f.lua`
source $SRC_DIR/.profile.d/kong-env
